// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFrWSdVoeU-MqMv6Y2CVG4u355YIkwFgc',
    appId: '1:500907750571:web:9a5bbb064347f05384f3ee',
    messagingSenderId: '500907750571',
    projectId: 'libelle-46e53',
    authDomain: 'libelle-46e53.firebaseapp.com',
    storageBucket: 'libelle-46e53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaa8I_mBt4USLLKbQYS3hDsqOIL44SrE0',
    appId: '1:500907750571:android:adc212437e93e3de84f3ee',
    messagingSenderId: '500907750571',
    projectId: 'libelle-46e53',
    storageBucket: 'libelle-46e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCRWlYzbJz0WnctyVDPdfxJXZOIVusoA',
    appId: '1:500907750571:ios:af8ad538baceb4c084f3ee',
    messagingSenderId: '500907750571',
    projectId: 'libelle-46e53',
    storageBucket: 'libelle-46e53.firebasestorage.app',
    iosBundleId: 'com.example.sensorvisualization25jp223wer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCRWlYzbJz0WnctyVDPdfxJXZOIVusoA',
    appId: '1:500907750571:ios:572325ce2cb3c37384f3ee',
    messagingSenderId: '500907750571',
    projectId: 'libelle-46e53',
    storageBucket: 'libelle-46e53.firebasestorage.app',
    iosBundleId: 'com.example.sensorvisualization',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFrWSdVoeU-MqMv6Y2CVG4u355YIkwFgc',
    appId: '1:500907750571:web:f08d8b869d7c3c9a84f3ee',
    messagingSenderId: '500907750571',
    projectId: 'libelle-46e53',
    authDomain: 'libelle-46e53.firebaseapp.com',
    storageBucket: 'libelle-46e53.firebasestorage.app',
  );
}
